### ISSUE TITLE
I can't make it work

### ISSUE THREAD

**Issue by goshko123** [wofsauge/External-Item-Descriptions#116] opened 2021-06-10 18:23 UTC
Hello
So I basically download the mod and I press the f2 button even try holding it but it doesn't seem to work can you explain what I need to do to fix this!

Thanks!!!

**Comment by wofsauge** [comment] 2021-06-10 22:26
can you tell me more about your install process, your game version, etc?

**Comment by goshko123** [comment] 2021-06-11 19:48
I just subscribed from steam workshop then restart the game and it didn't work. I checked the files but I think everything is fine. And I don't really know how to check the log I search everywhere but couldn't find it.

Also sorry for the slow respond but I had school.

**Comment by wofsauge** [comment] 2021-06-12 01:36
I would suggest that its caused by corrupt game files. To fix this, try:

1. unsubscribe from the mod
2. start the game so it uninstalls the mod. close the game
3. manually delete all the mods files left in the following directories:

steamapps\common\The Binding of Isaac Rebirth\mods\external item descriptions_836319872\

steamapps\common\The Binding of Isaac Rebirth\data\external item descriptions\

4. start the game again. close it again
5. Verify the integrity of your game files (right click on the game in steam -> properties -> game files)
6. subscribe to the mod
7. start the game and test if it fixed the issue

**Comment by goshko123** [comment] 2021-06-12 10:27
Thanks for the help. It worked. 

Thank you and I love your mod. <3

**Closed** 2021-06-12 10:27 UTC
