### ISSUE TITLE
Teleport 2.0 inaccuracies

### ISSUE THREAD

**Issue by biobak64** [wofsauge/External-Item-Descriptions#519] opened 2022-10-30 18:23 UTC
Teleport 2.0's reminder feature will always display "Normal Room" in Downpour 2 until the mirror world has been cleared, despite the item still teleporting Isaac in the correct order

The reminder feature also incorrectly predicts "I AM ERROR room" when all rooms in the Mausoleum II floor before the Ascent have been cleared, the game will keep sending Isaac to the Devil/Angel room instead

**Comment by wofsauge** [comment] 2022-11-05 17:04
The first bug is fixed now with commit 62b83cd

i cant reproduce the second issue. Its teleporting me into the I AM ERROR after visiting the devil/angel room.

**Comment by wofsauge** [comment] 2022-11-05 19:49
Second bug is fixed now as well :)

**Closed by wofsauge** 2022-11-05 19:49 UTC
