### ISSUE TITLE
Suggestion: Make Bag of Crafting Menu searchable

### ISSUE THREAD

**Issue by CreepSore** [wofsauge/External-Item-Descriptions#660] opened 2024-05-31 11:22 UTC
Hello

I wanted to make the request to make the Bag of Crafting Menu searchable, since searching is way faster when having multiple thousands of recipes calculated.

I implemented an own version looking like this (filtering is done inside the renderer function since it only gets filtered when redrawing):
![grafik](https://github.com/wofsauge/External-Item-Descriptions/assets/24907463/aca277f0-abbe-4e14-abc7-cba25114ae7f)

If wanted and needed I could take this on.
I just need to rewrite this thing into the eid_bagofcrafting.lua since i created an own file so I could hook into the main file better when the mod gets updated.

**Comment by wofsauge** [comment] 2024-05-31 11:26
looks like a promising feature. it would be nice if you could submit a pull request with your changes, so we can add the feature properly :)

**Comment by CreepSore** [comment] 2024-05-31 11:35
Ok sure I'll look into it :)
There are some things I still need to do to make the whole experience a little bit smoother though so it will need some time.
Are there any (coding-)guidelines i should know about?

**Comment by wofsauge** [comment] 2024-05-31 11:50
we have no coding guidelines written down, but here are some things that make it easier to maintain:
- Add comments to sections of code to help people understand what your code does
- Variable names should explain their usage
- Dont make functions to long
- All functions should be defined in the schema of `function EID:BoC________(arg1, arg2,...)` to make them extendable by other mods. that also makes them easily identifiable as part of the Bag of Crafting feature set
- If you add variables that are accessible by multiple functions, instead of making them local, try to add them to the `EID.BoC` variable table. that way the variable is accessible to other mods.
- If needed, make clear distinctions between Repentogon and Repentance code. we want to be 100% compatible for all versions of isaac.
- If you have workarounds somewhere in the code, add a comment to them to explain what they do

**Comment by wofsauge** [comment] 2024-05-31 11:55
Also: How will you handle keyboard players? how do they start / stop the search function, in order to make it not conflict with the general game-controls like moving or using items?

**Comment by CreepSore** [comment] 2024-05-31 12:08
The input is currently toggleable using CTRL +F (which sadly also toggles the fullscreen so I'll switch that to another key).
Currently I'm using `EID.bagPlayer.ControlsCooldown = 2`  to block any moving and item relevant inputs.
The only thing I'm struggling with currently is P (Pause) and F (Fullscreen) and other keys bound by mods.

I think the nicest solution to all of that would be a floating keyboard. That way we don't have to worry about bound keys since we handle the inputs at our own, and also the search would be accessible to controller users. Making this the default does destroy the intuitiveness by a lot though.

**Comment by CreepSore** [comment] 2024-05-31 12:36
So you'll just add a note that keys like F and P will not be blocked while searching?
I'll change the hotkey to the enter button, sounds like a good idea.

Another question:
The current behavior is that even when the search input is locked, the search filtering itself is still active until the whole query is deleted.
That way the recipes get locked even when not actively searching.

Also the `Search: <TEXT>` Line is now green or red respectively when the input is enabled or disabled.

Does that sound good?

**Comment by wofsauge** [comment] 2024-05-31 12:57
maybe its possible to block F and P Actions from being processed by the game, by using the MC_INPUT_ACTION callback. 
L is also a tricky button, because thats used by Mod Config menu. C is used by Dead Sea Scrolls.
I think with callback priority and the MC_INPUT_ACTION callback, those issues should maybe be fixable? thats needs to be tested.

> The current behavior is that even when the search input is locked, the search filtering itself is still active until the whole query is deleted.
That behavior needs to be playtested. i dont know what feels more intuitive in such a usecase. i would guess that a filtering only when the search is active would be less likely to cause user-errors. That way, people would not need to actively clear the search before seeing the full list again. On the other hand, we already have the "Lock List" feature. that can be used to lock the current search result.

> Also the Search: <TEXT> Line is now green or red respectively when the input is enabled or disabled.
i would not use Red, since thats a warning color. stay with white if the input is disabled and green when its enabled. 
Another thing to consider might be, to hide the search line when search is disabled and no query is locked. otherwise its just wasted space. We can add the search feature to the "controls info bar"- thingy as a way to advertise this feature.
I will also add a "Magnifying Glass" icon in the front of the search line, once your Pull request is merged.

**Comment by CreepSore** [comment] 2024-05-31 13:05
>I think with callback priority and the MC_INPUT_ACTION callback, those issues should maybe be fixable? thats needs to be tested.

Thanks, I'll test that.

>That behavior needs to be playtested. i dont know what feels more intuitive in such a usecase. i would guess that a filtering only when the search is active would be less likely to cause user-errors.

Maybe we could add an option into the Mod Config menu?
Shouldn't be that hard to implement both and that way users can choose what they prefer.
I would make the default your suggestion though.

> i would not use Red, since thats a warning color. stay with white if the input is disabled and green when its enabled.

Yeah that's what I figured too. Already changed that.

>Another thing to consider might be, to hide the search line when search is disabled and no query is locked. otherwise its just wasted space.

Already did that 👍

**Comment by CreepSore** [comment] 2024-05-31 15:01
MC_INPUT_ACTION worked for game actions (Fullscreen / Pause).

I also added a workaround for modded keybinds, which does work.
I don't know if that's appropiate though, so I'd appreciate it if you could take a look:

https://github.com/CreepSore/External-Item-Descriptions/commit/169143d5a9af9c127a936ddfb2b5169d129a70e3

**Comment by wofsauge** [comment] 2024-05-31 15:28
on first glance, that code should do the trick. 

I think i also like that the feature is in a separate file. makes the code a bit more readable in my opinion.

What we definitely should check out is, if adding the Input callback via the [:AddPriorityCallback() ](https://wofsauge.github.io/IsaacDocs/rep/ModReference.html#addprioritycallback) function does already do the trick and prevents mods like mod config menu from reading the inputs. that way we save ourselves the hooking of the input functions. Additionally, since the `MC_INPUT_ACTION ` callback gets executed like a thousand times per second, we should only add the inut callback function when the search feature is enabled. when its disabled, we call [:RemoveCallback()](https://wofsauge.github.io/IsaacDocs/rep/ModReference.html#removecallback) to improve the performance a bit even further.

On another note, why does this commit has whitespace changes in nearly every line of the original eid_bagofcrafting.lua file? is this caused by different line-endings or maybe some auto-formatter issue? We use Line ending style CRLF.

**Comment by CreepSore** [comment] 2024-05-31 17:50
>What we definitely should check out is, if adding the Input callback via the [:AddPriorityCallback() ](https://wofsauge.github.io/IsaacDocs/rep/ModReference.html#addprioritycallback)function does already do the trick and prevents mods like mod config menu from reading the inputs.

After some testing i've came to the conclusion that the MC_INPUT_ACTION callback seems to be a seperate logic than that from the Input functions.

>when its disabled, we call [:RemoveCallback()](https://wofsauge.github.io/IsaacDocs/rep/ModReference.html#removecallback) to improve the performance a bit even further.

Done 👍 

>On another note, why does this commit has whitespace changes in nearly every line of the original eid_bagofcrafting.lua file? is this caused by different line-endings or maybe some auto-formatter issue? We use Line ending style CRLF.

Fixed that, I'm working with LF by default on my machine.

I've also added some code-docs and squashed all commits into a new one:
https://github.com/CreepSore/External-Item-Descriptions/commit/6f218dde2fefb67f5121b9939be6bccdbba2a7bb

I still have to add the locking mode but other than that I don't have any other ideas anymore.

**Comment by CreepSore** [comment] 2024-05-31 17:53
![ex_01](https://github.com/wofsauge/External-Item-Descriptions/assets/24907463/8a8f3c45-4e1d-489a-a8bc-84ebd5b05b39)

Also, here's how it behaves currently

**Comment by wofsauge** [comment] 2024-05-31 18:14
that feature looks sweet! great job

**Closed** 2024-05-31 19:42 UTC
