### ISSUE TITLE
Wrong BFFs! synergy description for Sack of pennies and Bomb bag

### ISSUE THREAD

**Issue by FLESHNIK** [wofsauge/External-Item-Descriptions#673] opened 2024-06-12 14:31 UTC
<img width="712" alt="bffs_sack" src="https://github.com/wofsauge/External-Item-Descriptions/assets/20953914/8207a3cb-50dc-4c69-8810-22009fece04c">

<img width="712" alt="bffs_bomb" src="https://github.com/wofsauge/External-Item-Descriptions/assets/20953914/60a52fa6-4cbd-46ec-813d-d6e82799e871">

The wiki says that they have these synergies with BFFs!:
Sack of pennies: The familiar drops coins in a repeating pattern of 1, 2, 2 then 2 rooms.
Bomb bag: The familiar drops bombs in a repeating pattern of 2, 2 then 3 rooms.

**Comment by wofsauge** [comment] 2024-06-16 15:55
Thanks for the report. The issue is fixed now

**Closed** 2024-06-16 15:55 UTC

**Comment by magagnato4106** [comment] 2024-06-16 16:04
It's not the only one though. I found also another item with this problem but I don't remember which one!
